### ISSUE TITLE
Pipelines and Tools to run this app?

### ISSUE THREAD

**Issue by rprashantsingh** [tulitpal/tulit-sap-fortify#1]
Considering the current codebase and the app:
- How can I run this on a pipeline?
- What tools can be used to run the compiled version of this code (to mimic a pipeline)?
- How do we ensure the monitoring token stays valid?

**Comment by tulitpal** [comment]
- We can set up a CI/CD pipeline using Jenkins or CodeBuild + CodeDeploy to build and deploy our code.
- We can run the compiled version of this code on our local machines by importing it into, say, Eclipse with Tomcat.
- Currently in this code, the CIToken is hardcoded. But since the token can be generated by making one API call using the username and password, we can add one REST call to do that. The username and password can be maintained in a property file or in some secrets store.
